[package]
name = "budgeteer"
version = "0.1.2"
authors = ["Daniel Corn <info@corn.rest>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
chrono = "0.4"
serde = "1.0.94"
serde_json = "1.0.39"
serde_derive = "1.0.94"
reqwest = "0.9.18"
dialoguer="0.4.0"
console = "0.7.7"
ansi_term = "0.12.1"
