[package]
name = "budgeteer"
version = "0.1.3"
authors = ["Daniel Corn <info@corn.rest>"]
edition = "2021"

[dependencies]
clap = "2.33"
chrono = ">=0.4.20"
serde = "1.0.125"
serde_json = "1.0.64"
serde_derive = "1.0.125"
reqwest = { version = "^0.11.2", features = ["blocking"] }
dialoguer = { version = "^0.11.0", features = ["completion"] }
ansi_term = "0.12.1"
lazy_static = "1.4.0"
